/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

const supabaseUrl =
  import.meta.env.VITE_SUPABASE_URL ??
  "https://snkdhcqmpmfpvyrmhfya.supabase.co"

const publicAnonKeyValue =
  import.meta.env.VITE_SUPABASE_ANON_KEY ?? ""

export const projectId =
  supabaseUrl.match(/^https?:\/\/([^.]+)\.supabase\.co/)?.[1] ??
  "snkdhcqmpmfpvyrmhfya"

export const publicAnonKey = publicAnonKeyValue

export const supabaseConfig = {
  url: supabaseUrl,
  anonKey: publicAnonKeyValue,
  projectId,
}